In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
sns.set_style('whitegrid')

In [ ]:
# Regression
from sklearn.linear_model import LinearRegression

In [ ]:
data = pd.read_csv('sat.csv')

In [ ]:
data

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [ ]:
X = data['SAT']

In [ ]:
X

0     1714
1     1664
2     1760
3     1685
4     1693
      ... 
79    1936
80    1810
81    1987
82    1962
83    2050
Name: SAT, Length: 84, dtype: int64

In [ ]:
y = data['GPA']

In [ ]:
y

0     2.40
1     2.52
2     2.54
3     2.74
4     2.83
      ... 
79    3.71
80    3.71
81    3.73
82    3.76
83    3.81
Name: GPA, Length: 84, dtype: float64

In [ ]:
y.shape

(84,)

In [ ]:
reg = LinearRegression()

In [ ]:
reg.fit(np.array(X).reshape(-1,1),y)

LinearRegression()

In [ ]:
new_data = pd.DataFrame(data= [1740,1860], columns= ['SAT'])

In [ ]:
new_data

SAT
0  1740
1  1860

In [ ]:
reg.predict(new_data)

array([3.15593751, 3.35462007])

In [ ]:
reg.coef_

array([0.00165569])

In [ ]:
reg.intercept_

0.2750402996602803

In [ ]:
reg.score(np.array(X).reshape(-1,1),y)

0.40600391479679765

# Multiple Regression

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
data = pd.read_csv('multisat.csv')

In [ ]:
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [ ]:
X = data[['SAT','Rand 1,2,3']]

In [ ]:
X

SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [ ]:
y = data['GPA']

In [ ]:
mul_reg = LinearRegression()

In [ ]:
mul_reg.fit(X,y)

LinearRegression()

In [ ]:
mul_reg.coef_

array([ 0.00165354, -0.00826982])

In [ ]:
mul_reg.score(X,y)

0.40668119528142843

In [ ]:
from sklearn.feature_selection import f_regression

In [ ]:
f_regression(X,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [ ]:
f_regression(X,y) [1]

array([7.19951844e-11, 6.76291372e-01])

In [ ]:
p_value = f_regression(X,y) [1]

In [ ]:
p_value

array([7.19951844e-11, 6.76291372e-01])

In [ ]:
p_value.round(3)

array([0.   , 0.676])

In [ ]:
reg_summary = pd.DataFrame(data=['SAT','Rand 1,2,3'],columns=['features'])

In [ ]:
reg_summary

features
0         SAT
1  Rand 1,2,3

In [ ]:
reg_summary['coefficent'] = mul_reg.coef_

In [ ]:
reg_summary

features  coefficent
0         SAT    0.001654
1  Rand 1,2,3   -0.008270

In [ ]:
reg_summary['p_value'] = p_value.round(3)

In [ ]:
reg_summary

features  coefficent  p_value
0         SAT    0.001654    0.000
1  Rand 1,2,3   -0.008270    0.676