In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,3,4,6,4])

In [ ]:
arr

array([1, 3, 4, 6, 4])

In [ ]:
arr2=np.array([[2,5,3],[5,6,2],[7,88,21]])

In [ ]:
arr2

array([[ 2,  5,  3],
       [ 5,  6,  2],
       [ 7, 88, 21]])

In [ ]:
arr.shape

(5,)

In [ ]:
arr2.shape

(3, 3)

In [ ]:
list=[2,3,63,32,13,42]

In [ ]:
np.array(list)

array([ 2,  3, 63, 32, 13, 42])

In [ ]:
list2=[[1,2,4,3],[23,4,4,2]]

In [ ]:
arr4=np.array(list2)

In [ ]:
arr4.shape

(2, 4)

In [ ]:
arr4

array([[ 1,  2,  4,  3],
       [23,  4,  4,  2]])

In [ ]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(1,12,4)

array([1, 5, 9])

In [ ]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(7,18,9)

array([ 7.   ,  8.375,  9.75 , 11.125, 12.5  , 13.875, 15.25 , 16.625,
       18.   ])

In [ ]:
np.linspace(1,11,12)

array([ 1.        ,  1.90909091,  2.81818182,  3.72727273,  4.63636364,
        5.54545455,  6.45454545,  7.36363636,  8.27272727,  9.18181818,
       10.09090909, 11.        ])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(6)

array([0.64033755, 0.00097125, 0.82294403, 0.85765549, 0.93616737,
       0.88400586])

In [ ]:
np.random.rand(6,6)

array([[0.32942215, 0.582403  , 0.13797912, 0.51922816, 0.53621457,
        0.66794909],
       [0.97136609, 0.28686853, 0.04576614, 0.39642854, 0.03888202,
        0.8922563 ],
       [0.34799863, 0.3981054 , 0.39890316, 0.66794039, 0.14566001,
        0.23657538],
       [0.87807832, 0.72740488, 0.55313391, 0.01086696, 0.62895206,
        0.89363965],
       [0.66379854, 0.80262025, 0.49418463, 0.04502896, 0.43710589,
        0.65029398],
       [0.47132376, 0.4642948 , 0.91849043, 0.58980329, 0.34192581,
        0.26152087]])

In [ ]:
np.random.randn(6,7)

array([[-0.3241387 ,  2.29682658,  0.20026568,  0.72471655,  1.11013345,
        -2.23821014,  1.79459388],
       [ 0.19624125,  0.71736821,  1.7567098 ,  0.69030743,  0.21941941,
         0.12052781,  0.61755178],
       [ 0.3624653 , -0.18458584, -0.77695772, -0.30499742, -0.68597661,
        -0.59098301, -1.46630582],
       [ 1.50808249, -0.67480168,  0.05531001,  0.32159924,  0.21419583,
         1.86908727, -0.34817207],
       [-0.74790621, -1.00980671, -0.36115352,  1.0247586 , -0.79905735,
        -1.0112269 ,  0.19170372],
       [ 0.7381096 , -0.1554141 , -2.29402604,  0.83428663, -0.10084607,
         0.64161554,  0.87468588]])

In [ ]:
np.random.randint(6,54)

44

In [ ]:
np.random.randint(6,45,8)

array([17, 13, 28,  7, 29, 26, 21, 24])

In [ ]:
arr5=np.random.randint(6,45,8)

In [ ]:
arr5

array([35, 16, 21,  6, 39, 12,  9, 16])

In [ ]:
arr5.max()

39

In [ ]:
arr5.min()

6

In [ ]:
arr5.argmax()

4

In [ ]:
arr5.argmin()

3

In [ ]:
arr5.min()

6